//Auth types
export const USER_LOGIN_SUCCESS='USER_LOGIN_SUCCESS'
export const USER_LOGIN_START='USER_LOGIN_START'
export const USER_LOGIN_FAILED='USER_LOGIN_FAILED'
export const LOGOUT='LOGOUT'
export const CHANGE_PASSWORD='CHANGE_PASSWORD'